import Head from "next/head";
import Header from "../components/Header"; 

export default function Home() {
  return (
    <>
      <div className="">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <title>Amazon</title>
        </Head>

        <Header />
      </div>
    </>
  );
}
